### ISSUE TITLE
Clustering/incorporating shared-frailties/random-effects amongst groups

### ISSUE THREAD

**Issue by josephjzhao** [chjackson/flexsurv-dev#119]
Thank you for your wonderful package flexsurv. 

May I check if clustering/incorporating shared-frailties/random-effects amongst groups is possible with your package?

**Comment by chjackson** [comment]
Sorry it isn't, and there's no plans to implement this in flexsurv.  It's been a few years since I investigated how to do this, but packages that I know of which implement parametric survival models with frailties include [frailtypack](https://cran.r-project.org/web/packages/frailtypack/index.html) and [parfm](https://cran.r-project.org/web/packages/parfm/index.html).
