### ISSUE TITLE
Error "ltMatrices.c:139:56: error: expected ‘)’ before ‘FCONE’ F77_CALL(dtptri)(&lo, &di, &iJ, dans, &info FCONE FCONE);" when a try to reinstall the package flexsurv

### ISSUE THREAD

**Issue by moschito78** [chjackson/flexsurv-dev#166]
Hi, i received this error after i removed the package and i tried to reinstall it:

ltMatrices.c: In function ‘R_ltMatrices_solve’:
ltMatrices.c:139:56: error: expected ‘)’ before ‘FCONE’
             F77_CALL(dtptri)(&lo, &di, &iJ, dans, &info FCONE FCONE);
                                                        ^~~~~~
                                                        )
ltMatrices.c:144:66: error: expected ‘)’ before ‘FCONE’
             F77_CALL(dtpsv)(&lo, &tr, &di, &iJ, dans, dansx, &ONE FCONE FCONE FCONE);
                                                                  ^~~~~~
                                                                  )
ltMatrices.c: In function ‘R_syMatrices_chol’:
ltMatrices.c:375:47: error: expected ‘)’ before ‘FCONE’
         F77_CALL(dpptrf)(&lo, &iJ, dans, &info FCONE);
                                               ^~~~~~
                                               )
ltMatrices.c: In function ‘R_vectrick’:
ltMatrices.c:464:34: error: expected ‘)’ before ‘FCONE’
                         dans, &iJ FCONE FCONE FCONE FCONE);
                                  ^~~~~~
                                  )
ltMatrices.c:475:34: error: expected ‘)’ before ‘FCONE’
                         dans, &iJ FCONE FCONE FCONE FCONE);
                                  ^~~~~~
                                  )
make: *** [/usr/lib64/R/etc/Makeconf:167: ltMatrices.o] Error 1
ERROR: compilation failed for package ‘mvtnorm’
* removing ‘/usr/lib64/R/library/mvtnorm’
ERROR: dependency ‘mvtnorm’ is not available for package ‘bbmle’
* removing ‘/usr/lib64/R/library/bbmle’
ERROR: dependency ‘bbmle’ is not available for package ‘rstpm2’
* removing ‘/usr/lib64/R/library/rstpm2’
ERROR: dependencies ‘mvtnorm’, ‘rstpm2’ are not available for package ‘flexsurv’
* removing ‘/usr/lib64/R/library/flexsurv’

My R version is 3.6.0 (2019-04-26) -- "Planting of a Tree" on redhat 7.9.

Does anybody know what happened?

I thank anyone who can help me.

**Comment by chjackson** [comment]
Doesn't look like a `flexsurv` issue, rather an issue with installing `mvtnorm`, one of the packages it depends on.    That is a very old version of R you have, but https://cran.r-project.org/web/packages/mvtnorm/index.html claims to support R >=3.5.0, so I don't know.    

A similar error is reported at https://community.rstudio.com/t/rstudio-libraries-msm-and-mvtnorm-are-not-installing-on-linux-rh-rstudio-server-2023-06-0-build-4-2-1/168152/4, and a suggestion is made there to upgrade the C compiler.  Or install binaries (if these are available) rather than compiling from source.
