### ISSUE TITLE
error with left-censored observations

### ISSUE THREAD

**Issue by trobinj** [chjackson/flexsurv-dev#33]
I encountered an error from flexsurvreg with left-censored observations. The error may have something to do with the zero left endpoint as I was able to trick flexsurvreg into running without an error by adding a small time increment to the left endpoint of the interval of left-censored observations. To reproduce the error and the "fix" use the following script. 

```R
library(flexsurv)
library(coxinterval)

# Case where survreg works but flexsurvreg does not.

d <- cosmesis
d$left <- ifelse(d$left == 0, NA, d$left)

survreg(Surv(left, right, type = "interval2") ~ treat, dist = "lognormal", data = d)
flexsurvreg(Surv(left, right, type = "interval2") ~ treat, dist = "lognormal", data = d)

# Case where both survreg and flexsurvreg work (and agree) by modifying the left endpoint. 

d <- cosmesis
d$left <- ifelse(d$left == 0, 1e-05, d$left)

survreg(Surv(left, right, type = "interval2") ~ treat, dist = "lognormal", data = d)
flexsurvreg(Surv(left, right, type = "interval2") ~ treat, dist = "lognormal", data = d)
```

**Comment by chjackson** [comment]
Thanks for the report.   It looks like flexsurvreg was manipulating the data wrongly when only an upper bound was specified.  I think this is fixed in https://github.com/chjackson/flexsurv-dev/commit/f0fcea7adcc4c59298bedb7556d2c5791238ccd6.

Though I do think survreg (and flexsurvreg as a consequence) is harsh not to accept zero as a lower bound.  Zero might not be a valid event time, but it's the theoretically correct (open) lower bound for a left censored observation.

**Comment by trobinj** [comment]
Thank you for the quick fix. It's working fine for me now with that version.
