### ISSUE TITLE
log likelihood and right-censored data with pdist(inf) < 1

### ISSUE THREAD

**Issue by stephematician** [chjackson/flexsurv-dev#41]
I was considering interval/censored data in a context where it may not be the case that `S(t) -> 0` as `t -> inf`. Although this falls outside of some conventional survival analysis*, there's nothing really stopping someone from specifying a (cumulative) hazard function that tends to a finite value (for example, [pgompertz does not respect asymptote when q is infinite #34](https://github.com/chjackson/flexsurv-dev/issues/34))

It appears that if you do specify such a hazard/distribution function, the value at infinity is over-ridden inside `logLikFactory()` in [flexsurvreg.R](https://github.com/chjackson/flexsurv-dev/blob/master/R/flexsurvreg.R), particularly for right-censored data-points:

    pmax[pmaxargs$q==Inf] <- 1  # in case user-defined function doesn't already do this

Enforcing that value for the the (distribution) function within `logLikFactory` seems out of place, is there a good reason for doing so (aside from the comment)? I think it would make more sense to put the onus on the custom distributions having the correct value for _all_ non-null/non-na values of the `q` argument, including `Inf` (and `-Inf`; which might be useful when using `type='interval2'` Surv models?).

In any case, as it stands the log likelihood calculation will be incorrect if, say, `pgompertz()` is evaluated with `alpha` less than zero - or if a custom distribution does not obey `S(t) -> 0` as `t -> inf`, and you have right-censoring in your data.

*it's almost but not quite like a cure model

**Comment by stephematician** [comment]
On the other hand, thinking about right-censored data points, if someone did define a 'survival' function such that `S(t \to inf) > 0`, in all likelihood they are probably really trying to define a 'cure' model (ala Berkson and Gage 1952). If that were the case, the assignment `pmax[pmaxargs$q==Inf] <- 1` will result in the correct likelihood -- whether this was intended or not. 

Berkson, J., & Gage, R. P. (1952). Survival curve for cancer patients following treatment. Journal of the American Statistical Association, 47(259), 501-515. http://www.tandfonline.com/doi/abs/10.1080/01621459.1952.10501187

**Comment by chjackson** [comment]
Thanks for the considered report! 

I think the cumulative distribution function for a value of exactly q=Inf should always be 1, since the CDF is typically defined as P(X <= q), rather than P(X < q).    So, for the Gompertz with negative shape, although the CDF tends to a value c<1 as q tends to infinity, the value of the CDF at exactly Inf should still be 1,  as it's equal to the sum of c and the point mass of 1-c (the probability of living forever) at Inf. 

The code in logLikFactory is calculating the likelihood contribution for data points which are right-censored.  For such data points, we assume the person's death time could be anything greater than the censoring point, which includes the chance that they will live forever.  So in the context of this code, I think CDF=1 is appropriate.

**Comment by stephematician** [comment]
Thanks for the reply; I agree `p -> 1` as `t -> inf` will provide the correct likelihood for a right-censored observation as you describe (i.e. if the distribution approaches a number < 1, the remainder are 'cured' in the limit as t -> inf), do you think it might be worth making a comment along those lines in the documentation?

**Comment by chjackson** [comment]
Which part of the documentation were you thinking of?   At the moment it doesn't matter what a user's CDF returns at exactly Inf, because the value at Inf for any distribution is 1 by definition, thus enforced in the likelihood calculation, so I'm not sure what I would add to the manual section on custom distributions.
