### ISSUE TITLE
parametrization of gamma AFT model

### ISSUE THREAD

**Issue by FBartos** [chjackson/flexsurv-dev#92]
Hi,
the coefficients of the gamma model seem to be in the opposite direction than the remaining AFT families. I suspect that it is a bug (there is also a warning message about NaNs but I guess that it's unrelated).

```
flexsurvreg(Surv(recyrs, censrec) ~ group, data = bc, dist = "lognormal")
flexsurvreg(Surv(recyrs, censrec) ~ group, data = bc, dist = "llogis")
flexsurvreg(Surv(recyrs, censrec) ~ group, data = bc, dist = "gamma")
flexsurvreg(Surv(recyrs, censrec) ~ group, data = bc, dist = "gengamma")
flexsurvreg(Surv(recyrs, censrec) ~ group, data = bc, dist = "genf")
flexsurvreg(Surv(recyrs, censrec) ~ group, data = bc, dist = "weibull")
```

Best,
Frantisek

**Comment by chjackson** [comment]
This is intentional, for consistency with how the gamma is defined in base R, which by default uses the rate rather than the scale.   It's also consistent with the exponential. 

The new version has a new vignette where these covariate effects are explained: https://cran.r-project.org/web/packages/flexsurv/vignettes/distributions.pdf.  Note flexsurv is not designed specifically for AFT modelling, but for flexible modelling in general. 

The NaN warning messages are addressed in the development version, see https://github.com/chjackson/flexsurv-dev/issues/91

**Comment by FBartos** [comment]
I see. Sorry, I only checked the manual, not the vignettes. I understand the intention.
